apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: burakevci/not-defteri-api  # Docker Hub'a push ettiğin imaj adı
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "postgres"
        - name: DB_NAME
          value: "notes_db"
        - name: DB_USER
          value: "burak"
        - name: DB_PASS
          value: "1234"
